server:
    port: 8080
    contextPath: /client
    tomcat:
       uri-encoding: utf-8
security:
    basic:
        enabled: false

spring:
   thymeleaf:
     cache: false
   resources:
      cache-period: 0

config:
    oauth2:
        clientID: "e5b2c" 
        clientSecret: "ec5308be-1686-414b-b2d5-4eab0f84d95f" 
        accessTokenUri: http://bank.local:8111/storefront/oauth/token
        userAuthorizationUri: http://bank.local:8111/storefront/oauth/authorize
        resourceURI: http://bank.local:8111/storefront/facade/banks/piraeusbank/accounts/private
